### ISSUE TITLE
Use of integers in Lua expected results causes an unexpected abort

### ISSUE THREAD

**Issue by almostearthling** [almostearthling/whenever#28]
Using integer values for expected results while configuring Lua tasks or conditions causes **whenever** to abort. A configuration snippet like the following

```toml
[[condition]]
name = "Cond_LUA"
type = "lua"
tasks = ["SomeTask01"]
script = '''
    log.warn("Trace: *** TESTING CONDITION *** `" .. whenever_condition .. "`");
    a = 21 * 2;
    '''
expected_results = { a = 42 }
```

causes the configuration to fail, and **whenever** aborts as follows:

```txt
thread 'main' panicked at src\condition\lua_cond.rs:483:58:
called `Option::unwrap()` on a `None` value
```

This is due to the representation of a TOML integer as a float, which returns _None_ instead of the converted integer.
