### ISSUE TITLE
Check for presence of string like objects as keys of dictionaries in DBus

### ISSUE THREAD

**Issue by almostearthling** [almostearthling/whenever#49]
It should be possible to check that a dictionary resulting as output parameter from a DBus method call contains a string (or likewise an _object path_) among its keys. Using semantics similar to the `in` keyword in Python, which returns _True_ when checking for presence of an object in a _dict_ when the object is one of the keys (that is, `'a' in {'a': 1, 'b': 2}` yields _True_), the `"contains"` operator can be used in a way such that the following condition:

```toml
[[condition]]
name = "Cond_HasDisk01"
type = "dbus"
tasks = ["TRACE"]
bus = ":system"
service = "org.freedesktop.UDisks2"
object_path = "/org/freedesktop/UDisks2"
interface = "org.freedesktop.DBus.ObjectManager"
method = "GetManagedObjects"
parameter_check = """[{
    "index": 0,
    "operator": "contains",
    "value": "/org/freedesktop/UDisks2/block_devices/sda"
}]"""
```

is verified as long as `/org/freedesktop/UDisks2/block_devices/sda` is among the managed objects (which is often true).

In this particular case, moreover, the provided value has to be considered as an _object path_ instead of a string.
